<script>
  // 🌀⚡ Grain φ-Vortex Interactive Graincard
  // Tap-only navigation following Ken Wheeler's golden ratio geometry
  // Voice: Glow G2 (patient, hand-holding, first principles!)
  
  import { writable } from 'svelte/store';
  import { tweened } from 'svelte/motion';
  import { cubicOut } from 'svelte/easing';
  import { onMount } from 'svelte';

  // ============================================================================
  // 📊 PROPS & STATE
  // ============================================================================

  // Props: φ-data from Steel backend (JSON)
  export let phiData = null; // Will be loaded from phi-data.json
  export let graincardContent = ''; // Raw graincard markdown

  // State: Current vortex level (0 = full view, 5 = seed)
  let currentLevel = 0;
  let currentSection = 0; // Which of the 12 sections (0-11)

  // ============================================================================
  // 🌀 PHI CONSTANTS (Sacred Geometry!)
  // ============================================================================

  // These match the Steel backend constants!
  const PHI = 1.618033988749894;
  const PHI_CUBED = 4.236067977499789;
  const GOLDEN_ANGLE = 137.5077640500378;

  // ============================================================================
  // ⚡ TWEENED VALUES (Smooth Animations!)
  // ============================================================================

  // What are tweened values? They're reactive variables that animate smoothly!
  // When you change them, Svelte automatically interpolates between old and new.
  // Think of it like a smooth transition instead of a sudden jump! 🌊

  const zoom = tweened(1.0, {
    duration: 800, // 800ms = 0.8 seconds (feels natural!)
    easing: cubicOut // Ease out = fast start, slow end (like water flowing!)
  });

  const rotation = tweened(0, {
    duration: 800,
    easing: cubicOut
  });

  const opacity = tweened(1.0, {
    duration: 400,
    easing: cubicOut
  });

  // ============================================================================
  // 🌊 LOAD PHI DATA
  // ============================================================================

  // When component mounts, load the φ-data generated by Steel!
  onMount(async () => {
    if (!phiData) {
      try {
        const response = await fetch('/phi-data.json');
        phiData = await response.json();
        console.log('🌀 φ-data loaded!', phiData);
      } catch (error) {
        console.error('❌ Failed to load φ-data:', error);
        // Fallback: generate basic structure
        phiData = generateFallbackPhiData();
      }
    }
  });

  // Fallback if Steel hasn't generated phi-data.json yet
  function generateFallbackPhiData() {
    return {
      format: 'phi-vortex-graincard',
      version: '1.0',
      phi: PHI,
      phi_cubed: PHI_CUBED,
      golden_angle: GOLDEN_ANGLE,
      dimensions: {
        width: 100,
        height: 75,
        sections: 12
      },
      sections: Array.from({ length: 12 }, (_, i) => ({
        index: i,
        content: graincardContent || `Section ${i + 1}`,
        phi_coords: generatePhiCoords(25, 25, 5)
      }))
    };
  }

  // Generate φ-coordinates (client-side fallback)
  function generatePhiCoords(width, height, maxLevel) {
    return Array.from({ length: maxLevel + 1 }, (_, level) => {
      const scale = 1 / Math.pow(PHI, level);
      return {
        level,
        x: width * scale,
        y: height * scale,
        width: width * scale,
        height: height * scale,
        scale,
        rotation: (GOLDEN_ANGLE * level) % 360,
        vortex_depth: Math.min(width, height) / Math.pow(PHI_CUBED, level)
      };
    });
  }

  // ============================================================================
  // 🌀 TAP HANDLERS (The Core Interaction!)
  // ============================================================================

  // Tap anywhere = spiral inward by φ!
  // This is the main interaction - NO SCROLLING, just tapping! 🌊
  function spiralInward(event) {
    // Prevent if we're at maximum depth
    if (currentLevel >= 5) {
      // Flash animation to show we're at the seed!
      pulseAtSeed();
      return;
    }

    // Fade out slightly during transition
    opacity.set(0.7);
    
    // Move to next level
    currentLevel += 1;
    
    // Zoom in by factor of φ
    // Each level is 1/φ times the previous (61.8% size)
    zoom.set(1 / Math.pow(PHI, currentLevel));
    
    // Rotate by golden angle (137.5077°)
    // This creates the spiral pattern!
    rotation.set((GOLDEN_ANGLE * currentLevel) % 360);

    // Fade back in
    setTimeout(() => opacity.set(1.0), 200);

    // Play subtle sound? (Optional - could add later!)
    // playVortexSound(currentLevel);
  }

  // Tap back button = spiral outward by φ!
  function spiralOutward(event) {
    event?.stopPropagation(); // Don't trigger spiralInward!

    if (currentLevel <= 0) return;

    opacity.set(0.7);
    
    currentLevel -= 1;
    
    // Zoom out by factor of φ
    zoom.set(1 / Math.pow(PHI, currentLevel));
    
    // Rotate back
    rotation.set((GOLDEN_ANGLE * currentLevel) % 360);

    setTimeout(() => opacity.set(1.0), 200);
  }

  // Pulse animation when at seed (maximum depth)
  function pulseAtSeed() {
    // Quick pulse to show we're at the center!
    zoom.set(1 / Math.pow(PHI, currentLevel) * 1.1);
    setTimeout(() => {
      zoom.set(1 / Math.pow(PHI, currentLevel));
    }, 200);
  }

  // Keyboard navigation (bonus!)
  function handleKeydown(event) {
    switch (event.key) {
      case 'Enter':
      case ' ':
        spiralInward();
        break;
      case 'Escape':
      case 'Backspace':
        event.preventDefault();
        spiralOutward();
        break;
      case 'ArrowLeft':
        // Rotate counter-clockwise
        rotation.update(r => r - GOLDEN_ANGLE);
        break;
      case 'ArrowRight':
        // Rotate clockwise
        rotation.update(r => r + GOLDEN_ANGLE);
        break;
    }
  }

  // ============================================================================
  // 🎨 COMPUTED VALUES
  // ============================================================================

  // Get current section data
  $: currentSectionData = phiData?.sections?.[currentSection] || {
    content: graincardContent,
    phi_coords: []
  };

  // Get φ-coordinates for current level
  $: currentPhiCoords = currentSectionData.phi_coords?.[currentLevel] || {};

  // Calculate vortex depth percentage (for visual indicator)
  $: vortexDepthPercent = currentLevel === 0 ? 100 : 
    (100 / Math.pow(PHI_CUBED, currentLevel)).toFixed(1);

  // Check if we're at the seed (deepest level)
  $: atSeed = currentLevel >= 5;
</script>

<svelte:window on:keydown={handleKeydown} />

<style>
  /* ========================================================================
     🌀 φ-VORTEX GRAINCARD STYLES
     Ember Harvest theme: Dark aether + golden orange glow
     ======================================================================== */
  
  .graincard-container {
    width: 100vw;
    height: 100vh;
    overflow: hidden; /* NO SCROLLING! This is key! 🌊 */
    background: #1a1a1a; /* Dark like the aether */
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    position: relative;
    font-family: 'Courier New', 'Monaco', 'Menlo', monospace;
  }

  /* The main graincard vortex element */
  .graincard-vortex {
    font-family: 'Courier New', 'Monaco', 'Menlo', monospace;
    font-size: 14px;
    line-height: 1.2;
    color: #f4a460; /* Ember harvest orange! */
    white-space: pre-wrap;
    transform-origin: center center;
    padding: 2rem;
    border: 2px solid rgba(244, 164, 96, 0.3); /* Golden border */
    border-radius: 8px;
    background: rgba(0, 0, 0, 0.5);
    box-shadow: 0 0 40px rgba(244, 164, 96, 0.2); /* Golden glow! ⚡ */
    max-width: 90vw;
    max-height: 90vh;
    overflow: auto;
    transition: opacity 0.4s ease;
  }

  /* φ-markers show the golden ratio points */
  .phi-marker {
    position: absolute;
    width: 12px;
    height: 12px;
    border-radius: 50%;
    background: rgba(244, 164, 96, 0.6);
    box-shadow: 0 0 10px rgba(244, 164, 96, 0.8);
    pointer-events: none;
    animation: pulse 2s ease-in-out infinite;
  }

  @keyframes pulse {
    0%, 100% {
      transform: scale(1);
      opacity: 0.6;
    }
    50% {
      transform: scale(1.2);
      opacity: 0.9;
    }
  }

  /* Level indicator (top-left) */
  .level-indicator {
    position: fixed;
    top: 20px;
    left: 20px;
    color: rgba(244, 164, 96, 0.8);
    font-family: 'Courier New', monospace;
    font-size: 16px;
    pointer-events: none;
    text-shadow: 0 0 10px rgba(0, 0, 0, 0.8);
    line-height: 1.6;
  }

  /* Back button (bottom-left) */
  .back-button {
    position: fixed;
    bottom: 20px;
    left: 20px;
    padding: 12px 24px;
    background: rgba(244, 164, 96, 0.2);
    border: 2px solid rgba(244, 164, 96, 0.5);
    color: #f4a460;
    font-family: 'Courier New', monospace;
    font-size: 16px;
    cursor: pointer;
    border-radius: 8px;
    transition: all 0.3s ease;
    backdrop-filter: blur(10px);
  }

  .back-button:hover {
    background: rgba(244, 164, 96, 0.4);
    box-shadow: 0 0 20px rgba(244, 164, 96, 0.6);
    transform: translateY(-2px);
  }

  .back-button:active {
    transform: translateY(0);
  }

  /* Instructions (bottom-right) */
  .instruction {
    position: fixed;
    bottom: 20px;
    right: 20px;
    color: rgba(244, 164, 96, 0.6);
    font-family: 'Courier New', monospace;
    font-size: 14px;
    text-align: right;
    line-height: 1.6;
    pointer-events: none;
    text-shadow: 0 0 10px rgba(0, 0, 0, 0.8);
  }

  /* Golden spiral overlay (SVG) */
  .golden-spiral {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 80%;
    height: 80%;
    pointer-events: none;
    opacity: 0.15;
  }

  /* Seed indicator (when at deepest level) */
  .seed-indicator {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    font-size: 48px;
    opacity: 0.3;
    pointer-events: none;
    animation: glow 2s ease-in-out infinite;
  }

  @keyframes glow {
    0%, 100% {
      text-shadow: 0 0 20px rgba(244, 164, 96, 0.5);
    }
    50% {
      text-shadow: 0 0 40px rgba(244, 164, 96, 0.8);
    }
  }

  /* Responsive: smaller screens */
  @media (max-width: 768px) {
    .graincard-vortex {
      font-size: 12px;
      padding: 1rem;
    }
    
    .level-indicator,
    .instruction {
      font-size: 12px;
    }

    .back-button {
      padding: 8px 16px;
      font-size: 14px;
    }
  }
</style>

<!-- Main container - tap anywhere to spiral inward! -->
<div class="graincard-container" on:click={spiralInward}>
  
  <!-- Level indicator (top-left) -->
  <div class="level-indicator">
    ⚡ Level {currentLevel} / 5<br>
    φ⁻{currentLevel} = {(1 / Math.pow(PHI, currentLevel)).toFixed(3)}<br>
    Rotation: {($rotation).toFixed(1)}°<br>
    Depth: {vortexDepthPercent}%
  </div>

  <!-- Golden spiral overlay (subtle!) -->
  <svg class="golden-spiral" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid meet">
    <!-- Fibonacci spiral path -->
    <path 
      d="M 50,50
         Q 65,35 75,50
         T 80,70
         T 70,85
         T 45,90
         T 20,80
         T 15,50
         T 25,25
         T 55,20
         T 80,35"
      fill="none"
      stroke="rgba(244, 164, 96, 0.3)"
      stroke-width="1.5"
      stroke-linecap="round"
    />
    
    <!-- φ-markers along the spiral -->
    {#each [0, 1, 2, 3, 4, 5] as level}
      <circle
        cx={50 + 30 * Math.cos((GOLDEN_ANGLE * level * Math.PI) / 180)}
        cy={50 + 30 * Math.sin((GOLDEN_ANGLE * level * Math.PI) / 180)}
        r={3 / (level + 1)}
        fill="rgba(244, 164, 96, {0.6 - level * 0.1})"
      />
    {/each}
  </svg>

  <!-- The graincard vortex (animated with tweened values!) -->
  <div 
    class="graincard-vortex"
    style="
      transform: scale({$zoom}) rotate({$rotation}deg);
      opacity: {$opacity};
    ">
    {@html currentSectionData.content || graincardContent || 'Loading φ-vortex...'}
  </div>

  <!-- Seed indicator (when at deepest level) -->
  {#if atSeed}
    <div class="seed-indicator">⚡</div>
  {/if}

  <!-- Back button (spiral outward!) -->
  {#if currentLevel > 0}
    <button 
      class="back-button" 
      on:click|stopPropagation={spiralOutward}
      aria-label="Spiral outward">
      ← Back (φ⁺¹)
    </button>
  {/if}

  <!-- Instructions (bottom-right) -->
  <div class="instruction">
    {#if currentLevel === 0}
      ⚡ TAP ANYWHERE<br>
      to spiral inward by φ<br>
      <br>
      🌀 Each tap = ÷φ zoom<br>
      + {GOLDEN_ANGLE.toFixed(1)}° rotation
    {:else if atSeed}
      ⚡ AT THE SEED<br>
      Dielectric inertial plane!<br>
      <br>
      ← Tap back to spiral out
    {:else}
      ⚡ TAP to go deeper<br>
      ← or BACK to return<br>
      <br>
      Level {currentLevel}/5 - {vortexDepthPercent}% depth
    {/if}
  </div>
</div>





