#!/bin/bash
# Grain Network Module Deployment Script
# Generated by deploy-grainstore-modules.bb

set -e

echo "🌾 Grain Network Module Deployment"
echo "================================"

MODULES=(
  "clojure-google-drive-mcp"
  "clojure-icp"
  "clojure-s6"
  "clojure-s6-alias"
  "clojure-sixos"
  "clotoko"
  "grain-metatypes"
  "grain-nightlight"
  "grainbarrel"
  "graincamera"
  "graincasks"
  "grainclay"
  "grainconv"
  "graindaemon"
  "graindisplay"
  "graindrive"
  "graindroid"
  "grainicons"
  "grainlexicon"
  "grainmusic"
  "grainneovedic"
  "grainpack"
  "grainpbc"
  "grainsource"
  "grainspace"
  "grainweb"
  "grainwifi"
  "grainwriter")

echo "Deploying ${#MODULES[@]} modules to GitHub and Codeberg..."
echo

for module in "${MODULES[@]}"; do
  echo "📦 Deploying $module..."
  
  # Create GitHub repository
  echo "  Creating GitHub repository..."
  gh repo create grainpbc/$module --public --description "$module - Grain Network module"
  
  # Create Codeberg repository
  echo "  Creating Codeberg repository..."
  # Note: Codeberg CLI not available, manual creation required
  
  # Add remotes
  cd grainstore/$module
  git remote add github https://github.com/grainpbc/$module.git
  git remote add codeberg https://codeberg.org/grainpbc/$module.git
  
  # Generate README with dual URLs
  # (README generation would go here)
  
  # Push to both platforms
  git push github main
  git push codeberg main
  
  cd ../..
  echo "  ✅ $module deployed"
  echo
done

echo "🎉 All modules deployed successfully!"
echo "Next: Enable Pages on both platforms"
